version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8090:8090"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "90:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
